### ISSUE TITLE
M-Sh-97 Command getCommand() bug

### ISSUE THREAD

**Issue by maxkrivich** [dimalit/ChatApp#10]
Шаги по воспроизведению проблемы:
CommandListenerThread при запуске в строке 36 вызов receive() в котором композиция функций Scanner'a и getCommand(). Scanner читает из потока obj.nextLine() до '\n',  и передается строка без '\n'. В getCommand() идет проверка на наличие '\n' в строке, следовательно все условия false.

Ожидаемый результат:
Команда

Фактический результат:
null

**Comment by dimalit** [comment]
Эй! Зачем мне тут баги в программе Шафоростова? Ему в репо и пиши!
