### ISSUE TITLE
Не инициализирует имя в чате

### ISSUE THREAD

**Issue by ElenVM** [dimalit/ChatApp#13]
Шаги по воспроизведению проблемы:
1.Запустить ChatApp.
2.Авторизация(ввести ник цифрами , нажать "Apply").
3.Позвонить одному человеку.
4.Отправить сообщение.

Ожидаемый результат:
Имя отправителя инициализирует, возле даты сообщения.

Фактический результат:
При отправки сообщение, имя отправителя инициализирует, как "unnamed".

**Comment by M61Shaforostov** [comment]
Не подтверждаю: фактический результат совпадает с ожидаемым.
