### ISSUE TITLE
Не работает подключение

### ISSUE THREAD

**Issue by ipehov** [dimalit/ChatApp#18]
Шаги по воспроизведению проблемы:
1. Запустить Chat App.
2. Ввести свой ник (необязательно) и ip-адрес друга в поле remote IP, и нажать connect.

Ожидаемый результат:
Работающее подключение и возможность переписываться.

Фактический результат: 
Ошибка "Could not connection"

**Comment by vldmrshkvrk** [comment]
Рискну предположить, что кто-то не проложил порт, перед тем как переписываться

**Comment by dimalit** [comment]
Не знаю, к кому коннектился @addep7y, но к боту подключается.
