### ISSUE TITLE
 нет отправки статуса оффлайн

### ISSUE THREAD

**Issue by ElenVM** [dimalit/ChatApp#23]
Шаги по воспроизведению проблемы:
1. Запустить ChatApp .
2. Подключаемся к абоненту.
3. Невозможно подключится к абоненту, нет связи.

Ожидаемый результат:
При закрытии программы статус абонента в БД оффлайн.

Фактический результат:
Абонент онлайн.

**Comment by dimalit** [comment]
Нет. Решать за кого-то, что он оффлайн - как-то неэтично...
