### ISSUE TITLE
GUI 

### ISSUE THREAD

**Issue by maxkrivich** [dimalit/ChatApp#24]
JLable "Contacts" наезжает немного где-то 2-3 пикселя на поле с сообщениями

![sadasdasd](https://cloud.githubusercontent.com/assets/12199867/11508746/6200f30a-986b-11e5-8c48-3d181d48d541.png)

**Comment by dimalit** [comment]
Не, ну это ты придрался...

**Comment by maxkrivich** [comment]
Я такой. А мне вы за это бал бы снизили

**Comment by koha26** [comment]
На КВН это бы зашло :D ахаха

**Comment by maxkrivich** [comment]
Что?
